"""empty message

Revision ID: 663c79d7be3b
Revises: 6a20b04ccc08
Create Date: 2024-06-11 09:50:03.702227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663c79d7be3b'
down_revision = '6a20b04ccc08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
